### ISSUE TITLE
KeyError: "word '3' not in vocabulary"

### ISSUE THREAD

**Issue by Chuan1997** [benedekrozemberczki/diff2vec#3]
I construct my custom edgelist.csv as instructed, and this error shows up:
2020-10-25 15:10:28,162 : INFO : training on a 8376460 raw words (8376460 effect
ive words) took 143.0s, 58587 effective words/s
Traceback (most recent call last):
  File ".../src/diffusion_2_vec.py", line 121, i
n <module>
    main(args)
  File ".../src/diffusion_2_vec.py", line 117, i
n main
    learn_pooled_embeddings(walks, counts, args)
  File ".../src/diffusion_2_vec.py", line 63, in
 learn_pooled_embeddings
    save_embedding(args, model, counts)
  File ".../src/diffusion_2_vec.py", line 95, in
 save_embedding
    out.append([int(node)-1] + list(model.wv[str(node-1)]))
  File "D:\Anaconda3\envs\py36\lib\site-packages\gensim\models\keyedvectors.py",
 line 353, in __getitem__
    return self.get_vector(entities)
  File "D:\Anaconda3\envs\py36\lib\site-packages\gensim\models\keyedvectors.py",
 line 471, in get_vector
    return self.word_vec(word)
  File "D:\Anaconda3\envs\py36\lib\site-packages\gensim\models\keyedvectors.py",
 line 468, in word_vec
    raise KeyError("word '%s' not in vocabulary" % word)
KeyError: "word '3' not in vocabulary"

How could I solve this problem?

**Comment by benedekrozemberczki** [comment]
What is your node indexing?

**Comment by Chuan1997** [comment]
I checked my node indexing, and found that there is no node '3' in edgelist, so this error happened.
So I tried to add self-loop to the original adjacency matrix to avoid this problem, and there is other error:
![11](https://user-images.githubusercontent.com/34181999/97127082-a319ff80-1773-11eb-8727-8f52047f3f20.png)

the edgelist is like:
![22](https://user-images.githubusercontent.com/34181999/97127090-aad9a400-1773-11eb-925d-d2e4c0c0c0c0.jpg)

**Comment by benedekrozemberczki** [comment]
I would recommend using the Diff2Vec implementation in Karate Club. You can use that very easily. Can you star that repo and hit follow here on GitHub?
